/*
 * generated by Xtext 2.10.0
 */
package org.xtext.t3.turtle.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTurtleScopeProvider extends DelegatingScopeProvider {
}
