/**
 * generated by Xtext 2.10.0
 */
package org.xtext.t3.turtle.turtle;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Forward</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.t3.turtle.turtle.TurtlePackage#getForward()
 * @model
 * @generated
 */
public interface Forward extends Command
{
} // Forward
