/*
 * generated by Xtext 2.10.0
 */
package org.xtext.t3.turtle.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.xtext.t3.turtle.turtle.Model

/**
 * Teste tirados de http://mia.openworldlearning.org/logo.htm
 */
@RunWith(XtextRunner)
@InjectWith(TurtleInjectorProvider)
class TurtleParsingTest{

	@Inject
	ParseHelper<Model> parseHelper

	@Test 
	def void forwardTest() {
		val result = parseHelper.parse('''
			fd 30
		''')
		Assert.assertNotNull(result)
		Assert.assertEquals(0, result.eResource.errors.size)
	}
	
	@Test 
	def void rotateTest() {
		val result = parseHelper.parse('''
			rt 60
		''')
		Assert.assertNotNull(result)
		Assert.assertEquals(0, result.eResource.errors.size)
	}
	
	@Test 
	def void forwardRotateTest() {
		val result = parseHelper.parse('''
			fd 30 rt 60
		''')
		Assert.assertNotNull(result)
		Assert.assertEquals(0, result.eResource.errors.size)
	}
	
	@Test 
	def void repeatTest() {
		val result = parseHelper.parse('''
			repeat 3 [fd 30 rt 60]
		''')
		Assert.assertNotNull(result)
		Assert.assertEquals(0, result.eResource.errors.size)
	}
	
}