/**
 * generated by Xtext 2.10.0
 */
package org.xtext.t3.turtle.turtle.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.t3.turtle.turtle.Forward;
import org.xtext.t3.turtle.turtle.TurtlePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Forward</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ForwardImpl extends CommandImpl implements Forward
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ForwardImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TurtlePackage.Literals.FORWARD;
  }

} //ForwardImpl
