/*
 * generated by Xtext 2.10.0
 */
package org.xtext.t3.turtle.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import pucrs.lp.turtle.ui.internal.TurtleActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TurtleExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TurtleActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TurtleActivator.getInstance().getInjector(TurtleActivator.ORG_XTEXT_T3_TURTLE_TURTLE);
	}
	
}
